# Use Node.js for building the app
FROM node:14


# Set the working directory
WORKDIR /app


# Clone the repository
RUN git clone https://github.com/ianmeinert/dashboard.git .


# Navigate to the frontend directory
WORKDIR /app/frontend


# Install dependencies
RUN npm install


# Build the application
RUN npm run build


# Expose the port that the app will run on
EXPOSE 4173


# Command to serve the app using Node.js
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]