version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"  # Map container port 5173 to host port 5173
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8081
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8081:8081"
    env_file:
      - ./.env
